# Generated by Django 2.2.24 on 2024-06-18 18:37

from django.db import migrations
import phonenumbers

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20240618_2109'),
    ]

    def fill_pure_phonenumber(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        flats = Flat.objects.all()
        for flat in flats.iterator():
            owner_pure_phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')
            if not phonenumbers.is_valid_number(owner_pure_phonenumber):
                flat.owner_pure_phone = owner_pure_phonenumber
            flat.save()

    operations = [
        migrations.RunPython(fill_pure_phonenumber)
    ]
