# Generated by Django 2.2.24 on 2024-06-18 18:37

from django.db import migrations
import phonenumbers

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20240618_2109'),
    ]

    def fill_pure_phonenumber(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        for flat in Flat.objects.all().iterator():
            phone_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
            if phonenumbers.is_valid_number_for_region(phone_number, 'RU'):
                flat.owner_pure_phone = f'+{phone_number.country_code}{phone_number.national_number}'
            else:
                flat.owner_pure_phone = ''
            flat.save()

    operations = [
        migrations.RunPython(fill_pure_phonenumber)
    ]
