# Generated by Django 2.2.24 on 2024-06-18 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20240618_2158'),
    ]

    def fill_flat(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        Owner = apps.get_model('property', 'Owner')
        for flat in Flat.objects.all():
            flat.flat_owners.set(
                Owner.objects.filter(
                    owner=flat.owner,
                    owners_phonenumber=flat.owners_phonenumber,
                )
            )


    operations = [
        migrations.RunPython(fill_flat)
    ]
